var version_diff_flow_ref_Release_1_9 = {
  "node":[{
      "change":"modified",
      "display_name":"<span class=\"hasTooltip\" data-reftooltip=\"node_Effects___Effect_Resource\" data-reftooltip-refid=\"flow_ref\"><a class=\"el\" href=\"cat_Effects.html#node_Effects___Effect_Resource\">Effects > Effect Resource</a></span>",
      "details":"<table class='paramTable'><tr><td style='border:none'><span class='paramTableCaption'>Inputs</span></td></tr><tr class='version-removed-inner'><td class=\"paramTableNameCell\"><p align=\"right\"><span class=\"builtInType hasTooltip\" data-tooltip=\"string\" data-tooltip-refid=\"flow_ref\">string</span></p></td><td class=\"paramTableNameCell\"><p><span style=\"width:10px; height:10px; background-color:#923930; border-radius:5px; -webkit-border-radius: 5px; -moz-border-radius: 5px; display:inline-block\"></span></p></td><td style=\"min-width:125px\" class=\"paramTableNameCell argument\" align=\"left\"><p translate=\"no\"><b style=\"color:#923930\">Resource</p></td><td class=\"paramTableNameCell\"><p><img src='icon_flow_editable.png' height='16' width='16' style='vertical-align:-3px' class='hasTooltip' data-reftooltip='icon_flow_editable' data-reftooltip-refid='flow_ref'  /></p></td><td class=\"paramTableNameCell\"><p></p></td><td class=\"paramTableDocCell\"></td></tr><tr class='version-added-inner'><td class=\"paramTableNameCell\"><p align=\"right\"><span class=\"builtInType hasTooltip\" data-tooltip=\"string\" data-tooltip-refid=\"flow_ref\">string</span></p></td><td class=\"paramTableNameCell\"><p><span style=\"width:10px; height:10px; background-color:#923930; border-radius:5px; -webkit-border-radius: 5px; -moz-border-radius: 5px; display:inline-block\"></span></p></td><td style=\"min-width:125px\" class=\"paramTableNameCell argument\" align=\"left\"><p translate=\"no\"><b style=\"color:#923930\">Effect</p></td><td class=\"paramTableNameCell\"><p><img src='icon_flow_editable.png' height='16' width='16' style='vertical-align:-3px' class='hasTooltip' data-reftooltip='icon_flow_editable' data-reftooltip-refid='flow_ref'  /></p></td><td class=\"paramTableNameCell\"><p></p></td><td class=\"paramTableDocCell\"></td></tr></table>",
      "version":"Release 1.9",
      "name":"Effects > Effect Resource"
    }]
};
